Repository GollaBharath/Gamify, pull requests merged in 2025-08, with the labels that each got.

#34 issue create automate message added
  .github/workflows/issue-create-automate-message.yml
Labels: GSSoC, Level 1, OSCI

#43 fix: normalize email case and whitespace in auth
  server/controllers/authController.js
Labels: bug, enhancement, GSSoC, Level 1, OSCI

#60 Added .env.example file for client & server
  client/.env.example
  server/.env.example
Labels: enhancement, Level 1, OSCI

#57 added scroll to top button
  client/src/App.jsx
  client/src/components/ScrollToTopButton.jsx
Labels: GSSoC, Level 1
