Repository GollaBharath/Gamify, pull requests merged in 2025-09, with the labels that each got.

#77 Standardize getProfile controller for consistency
  client/.gitignore
  server/controllers/authController.js
  server/controllers/userController.js
Labels: enhancement, GSSoC'25, level2

#81 fix: text overflow in Featured Templates section
  client/src/components/Home.jsx
Labels: bug, 1 ⭐, OSCI'25

#85 Enhancing user experience by Static Chatbot
  client/public/icons/close_small_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png
  client/public/icons/send.png
  client/public/icons/sports.png
  client/src/App.jsx
  client/src/components/chatbot.css
  client/src/components/chatbot.jsx
Labels: enhancement, GSSoC'25, 2⭐⭐, level 2
